CREATE DATABASE Forum;
CREATE TABLE ThanhVien(
MaTV INT PRIMARY KEY,
TenTV VARCHAR (30),
PassworkTV VARCHAR (30)
);
CREATE TABLE ChuDe(
MaCD INT PRIMARY KEY,
TenCD VARCHAR (255)
);
CREATE TABLE BaiViet(
MaBV INT PRIMARY KEY,
Title VARCHAR (255),
NoiDung LONGTEXT,
MaTV INT,
FOREIGN KEY (MaTV) REFERENCES ThanhVien(MaTV),
MaCD INT,
FOREIGN KEY (MaCD) REFERENCES ChuDe(MaCD),
parentMaBV INT,
FOREIGN KEY (parentMaBV) REFERENCES BaiViet (MaBV)
);
drop TABLE BaiViet;
drop TABLE ThanhVien;
drop TABLE ChuDe;
drop DATABASE Forum;
